// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6CPy_tE-o7WMYXs1MQF0NYSKWC2f51pI',
    appId: '1:519180059555:web:5c975eee1c679415c01016',
    messagingSenderId: '519180059555',
    projectId: 'h4scrumboard',
    authDomain: 'h4scrumboard.firebaseapp.com',
    storageBucket: 'h4scrumboard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfujYcsUXQklXarOlKsazeclHt-Q2-U7w',
    appId: '1:519180059555:android:f8e5515bd2f8cf2dc01016',
    messagingSenderId: '519180059555',
    projectId: 'h4scrumboard',
    storageBucket: 'h4scrumboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzW6hk0jWVjaDTUigcLUlUPXcqTnkp3oM',
    appId: '1:519180059555:ios:84f09320ea0f3fe8c01016',
    messagingSenderId: '519180059555',
    projectId: 'h4scrumboard',
    storageBucket: 'h4scrumboard.appspot.com',
    iosClientId: '519180059555-93qaj1ui7bqv06nur01blkv1gd8fbbtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzW6hk0jWVjaDTUigcLUlUPXcqTnkp3oM',
    appId: '1:519180059555:ios:84f09320ea0f3fe8c01016',
    messagingSenderId: '519180059555',
    projectId: 'h4scrumboard',
    storageBucket: 'h4scrumboard.appspot.com',
    iosClientId: '519180059555-93qaj1ui7bqv06nur01blkv1gd8fbbtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
